import {
  imageone,
  imagetwo,
  imagethree,
  imagefour,
  imagefive,
  imagesix,
  imageseven,
  imageeight,
  imagenine,
  imageten,
} from "../../images/RuiruMugutha";
import {
  imageonerm,
  imagetworm,
  imagethreerm,
  imagefourrm,
  imagefiverm,
  imagesixrm,
  imagesevenrm,
  imageeightrm,
  imageninerm,
  imagetenrm,
} from "../../images/RuiruMwmbley";
import {
  imageonerk,
  imagetwork,
  imagethreerk,
  imagefourrk,
  imagefiverk,
  imagesixrk,
  imagesevenrk,
  imageeightrk,
  imageninerk,
  imagetenrk,
} from "../../images/RuiruKimbo";
import {
  imageonek,
  imagetwok,
  imagethreek,
  imagefourk,
  imagefivek,
  imagesixk,
} from "../../images/Katani";
import {
  imageonerms,
  imagetworms,
  imagethreerms,
  imagefourrms,
} from "../../images/RuiruMwmbleySale";
import {
  imageonermj,
  imagetwormj,
  imagethreermj,
  imagefourrmj,
  imagefivermj,
  imagesixrmj,
  imagesevenrmj,
  imageeightrmj,
  imageninermj,
  imagetenrmj,
} from "../../images/RuiruMatangiJunction";
import {
  imageonermsec,
  imagetwormsec,
  imagethreermsec,
  imagefourrmsec,
  imagefivermsec,
  imagesixrmsec,
  imagesevenrmsec,
  imageeightrmsec,
  imageninermsec,
  imagetenrmsec,
} from "../../images/RuiruMatangi";
import {
  imageonerb,
  imagetworb,
  imagethreerb,
  imagefourrb,
  imagefiverb,
  imagesixrb,
  imagesevenrb,
  imageeightrb,
  imageninerb,
  imagetenrb,
} from "../../images/RuiruBypassKamakis";
import {
  imageonermk,
  imagetwormk,
  imagethreermk,
  imagefourrmk,
  imagefivermk,
  imagesixrmk,
  imagesevenrmk,
  imageeightrmk,
  imageninermk,
  imagetenrmk,
} from "../../images/RuiruMatangiKimbo";
import {
  imageonerN,
  imagetworbN,
  imagethreerN,
  imagefourrN,
  imagefiverN,
  imagesixrN,
  imagesevenrN,
  imageeightrN,
  imageninerN,
  imagetenrN,
} from "../../images/House11";

export const data = [
  {
    id: 1,
    images: [
      imageone,
      imagetwo,
      imagethree,
      imagefour,
      imagefive,
      imagesix,
      imageseven,
      imageeight,
      imagenine,
      imageten,
    ],
    description: `HOUSE ON SALE,
    7.8M Mortgage acceptable,
    3 bedroom master ensuite `,
    location: "In Ruiru Matangi ",
    price: "7.8M",
    parking: "4 cars",
    security: "Security with guards 24hrs",
    water: "Water flowing 24hrs",
    more: `40/80 corner plot, 
    Ready title, 
    In Ruiru Matangi, 
    3.5km from Thika Rd, 
    In controlled development community, 
    Water supply plenty and sufficient, 
    Electricity connected, 
    Internet services available, 
    Parking of 4 cars, 
    Sitting room is spacious, 
    Spacious dining room table,
    Open plan spacious kitchen fitted with wall to wall cabinets,
    Unique finishes,
    Superb painting and effects,
    Chandaria bulbs,  
    Laundry area, 
    Common separate toilet and bathroom, 
    All bedrooms are fitted with wall to wall wardrobes, 
    Spacious Master bedroom fitted with wall to wall wardrobes, 
    Hot shower connected, 
    Perimeter wall, 
    Security alarm system, 
    Alarm door bell, 
    Internet Connected,
    Compound of 6 cars,
    The house is close vicinity to Wankan ,Bethlehem, Liz Wanyoike ,Schools ,Spur Shopping mall and worship places,
    Mortgage acceptable.`,
  },
  {
    id: 2,
    images: [
      imageonerm,
      imagetworm,
      imagethreerm,
      imagefourrm,
      imagefiverm,
      imagesixrm,
      imagesevenrm,
      imageeightrm,
      imageninerm,
      imagetenrm,
    ],
    description: "HOUSE ON SALE 7.5M negotiable, 3 bedroom all ensuite ",
    location: "Ruiru Matangi",
    price: "7.5M neg",
    parking: "4 cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: `40/60 plot
    Ready title, 
    In Ruiru Matangi, 
    In controlled development community, 
    Water supply plenty and sufficient, 
    Electricity connected, 
    Internet services available, 
    Parking of 4 cars ,
    Sitting room is spacious, 
    Spacious dining room table, 
    Open plan spacious kitchen fitted with wall to wall cabinets,
    Unique finishes,
    Superb painting and effects,
    Chandaria bulbs,  
    Laundry area, 
    Common separate toilet and bathroom, 
    All bedrooms are ensuite and fitted with wall to wall wardrobes, 
    Spacious Master bedroom fitted with wall to wall wardrobes, 
    Hot shower connected, 
    Perimeter wall, 
    Security alarm system, 
    Alarm door bell, 
    Compound with concrete, 
    The house is close vicinity to Wankan ,Bethlehem, Liz Wanyoike ,Schools ,Spur Shopping mall and worship places,
    SELLING PRICE 7.5M Negotiable.`,
  },
  {
    id: 10,
    images: [
      imageonerN,
      imagetworbN,
      imagethreerN,
      imagefourrN,
      imagefiverN,
      imagesixrN,
      imagesevenrN,
      imageeightrN,
      imageninerN,
      imagetenrN,
    ],
    description: "HOUSE ON SALE 19.5M, Newly built Flatroof ",
    location: "Ruiru Matangi",
    price: "19.5M neg",
    parking: "4 cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: `4 bedroom all ensuite 
    Plus SQ,
    In a gated community, 
    In Ruiru Bypass, 
    1Km from Thika rd, 
    40 by 80 plot,
    Ready title, 
    Water supply sufficient, 
    Security with guards, 
    Parking of 4 cars,
    Lounge is spacious, 
    Family room,
    Dinning room table, 
    With unique finishes and design,
    Chandaria bulbs, 
    Gypsum ceiling, 
    Sunken wooden floor, 
    Open plan kitchen fitted with wall to wall cabinets, 
    Pantry room, 
    Laundry area, 
    Common separate toilet and bathroom, 
    Guest room is spacious and fitted with wall to wall closet,
    First floor consists, 
    Friendly staircases, 
    Family room,
    Closed balcony, 
    Open spacious window that gives penetrating light, 
    All bedrooms are fitted with wall to wall closet,
    With a large balcony, 
    Common separate toilet and bathroom, 
    Master bedroom is ensuite fitted with wall to wall closet, 
    All bathrooms are fitted with hot shower, 
    Alarm door bell, 
    Security alarm, 
    Compound with cabro, 
    Its close vicinity to Spur shopping mall, Quickmart shopping mall,schools and worship places, 
    ASKING PRICE 19.5M.`,
  },
  {
    id: 3,
    images: [imageonerms, imagetworms, imagethreerms, imagefourrms],
    description:
      "HOUSE ON SALE 17M NEWLY BUILT 4 bedroom all ensuite With a self contained SQ rooftop",
    location: "Ruiru Mwmbley 1 km from Thika Rd 400 metres from Eastern bypass",
    price: "17M",
    parking: "4 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "40*80 plot size ,Lounge is spacious, Dinning room table, With unique finishes and design, Chandaria bulbs, Gypsum ceiling, Tiled floor, Open plan kitchen fitted with wall to wall cabinets, Pantry room, Laundry area, Common separate toilet and bathroom, Guest room is spacious and fitted with wall to wall closet, First floor consist, Friendly staircases, Open spacious window that gives penetrating light, All bedrooms are ensuite fitted with wall to wall closet, With a large balcony, Common separate toilet and bathroom, Master bedroom is ensuite fitted with wall to wall closet, Master bathroom with bathtub, All bathrooms are fitted with hot shower, Alarm door bell, Security alarm, Compound with cabro, Its  close vicinity to Naivas shopping mall, schools and worship places, ASKING PRICE 17M",
  },
  {
    id: 4,
    images: [
      imageonek,
      imagetwok,
      imagethreek,
      imagefourk,
      imagefivek,
      imagesixk,
    ],
    description:
      "HOUSE ON SALE, 23M, NEWLY BUILT HOUSE, 4 bedroom all ensuite Plus self contained DSQ",
    location: "Katani",
    price: "23M",
    parking: "Parking is massive",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "In a 2 plots of 40 by 60 plot, Ready title, Lounge is spacious, Dinning room table, With unique finishes and design, Chandaria bulbs, Gypsum ceiling, Tiled floor, Spacious Open plan kitchen fitted with wall to wall modern cabinets, Pantry room, Laundry area, Common separate toilet and bathroom, Guest room is spacious and fitted with wall to wall closet, First floor consists, Friendly staircases, Open spacious window that gives penetrating light, All bedrooms are ensuite fitted with wall to wall closet, With a large balcony, Common separate toilet and bathroom, Master bedroom is ensuite fitted with wall to wall closet, All bathrooms are fitted with hot shower, Alarm door bell, Security alarm, Compound with cabro, Its close vicinity to shopping malls, schools and worship places, ASKING PRICE 23M",
  },
  {
    id: 5,
    images: [
      imageonerk,
      imagetwork,
      imagethreerk,
      imagefourrk,
      imagefiverk,
      imagesixrk,
      imagesevenrk,
      imageeightrk,
      imageninerk,
      imagetenrk,
    ],
    description: `HOUSE ON SALE,
      16M,
      NEWLY BUILT 
      4 bedroom all ensuite 
      With a self contained SQ`,
    location: "In Ruiru Membley, 1 Km from Thika Rd",
    price: "16M",
    parking: "3 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: `40*80 plot size
    Ready title, 
    Water supply sufficient, 
    Security with guards, 
    Parking of 3 cars,
    Lounge is spacious, 
    Dinning room table, 
    With unique finishes and design,
    Chandaria bulbs, 
    Gypsum ceiling, 
    Tiled floor, 
    Open plan kitchen fitted with wall to wall cabinets, 
    Pantry room, 
    Laundry area,
    Common separate toilet and bathroom, 
    Guest room is spacious and fitted with wall to wall closet,
    First floor consists, 
    Friendly staircases, 
    Open spacious window that gives penetrating light,
    All bedrooms are ensuite fitted with wall to wall closet,
    With a large balcony,
    Common separate toilet and bathroom, 
    Master bedroom is ensuite fitted with wall to wall closet,
    Master bathroom with bathtub,
    All bathrooms are fitted with hot shower, 
    Alarm door bell, 
    Security alarm, 
    Compound with cabro, 
    Its  close vicinity to Naivas shopping mall, schools and worship places`,
  },
  {
    id: 6,
    images: [
      imageonermsec,
      imagetwormsec,
      imagethreermsec,
      imagefourrmsec,
      imagefivermsec,
      imagesixrmsec,
      imagesevenrmsec,
      imageeightrmsec,
      imageninermsec,
      imagetenrmsec,
    ],
    description: "HOUSE ON SALE 37M NEWLY BUILT HOUSE, 4 bedromms all ensuite",
    location: "In Kenyatta  Rd From Thika Rd its 2km",
    price: "37M",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: `Plus Dsq,
    With a family Room,
    In a gated community, 
    In Kenyatta  Rd,
    From Thika Rd its 2km,
    1/4 acre,
    Ready Title,
    Water supply sufficient, 
    Security with guards 24 hrs,
    Parking is massive,  
    With modern finishes and effects, 
    Lounge is spacious, 
    Dinning room table, 
    With unique finishes and design,
    Sunken wooden floor,
    Open plan kitchen fitted with wall to wall cabinets, 
    Pantry room, 
    Laundry area, 
    Common separate toilet and bathroom, 
    Guest room is spacious and fitted with wall to wall closet,
    First floor consists, 
    Friendly staircases, 
    Open spacious window that gives penetrating light, 
    All bedrooms are ensuite and fitted with wall to wall closet,
    With a large balcony, 
    Common separate toilet and bathroom, 
    Master bedroom is ensuite fitted with a walking inn wall to wall closet, 
    All bathrooms are fitted with hot shower, 
    Alarm door bell, 
    Security alarm,
    Compound with cabro, 
    Well manicured grass and flower garden, 
    Its  close vicinity to shopping mall, school and worship places, 
    SELLING PRICE 37M.`,
  },
  {
    id: 7,
    images: [
      imageonermj,
      imagetwormj,
      imagethreermj,
      imagefourrmj,
      imagefivermj,
      imagesixrmj,
      imagesevenrmj,
      imageeightrmj,
      imageninermj,
      imagetenrmj,
    ],
    description:
      "HOUSE ON SALE, 6.5M, NEWLY BUILT FLAT ROOF,3 bedroom, master ensuite",
    location: "Ruiru Matangi Junction",
    price: "6.5M",
    parking: "4 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "40 by 60 plot, Ready title, Electricity connected, Internet services available, Sitting room is spacious, Spacious dining room table, Open plan spacious kitchen fitted with wall to wall cabinets, Unique  finishes, Chadaria bulbs, Superb painting and effects,  Laundry area, Common separate toilet and bathroom, All bedrooms are fitted with wall to wall wardrobes, Spacious Master bedroom is ensuite fitted with wall to wall wardrobes, Hot shower connected, Perimeter wall, Security alarm system, Alarm door bell, ASKING  PRICE 6.5M",
  },
  {
    id: 8,
    images: [
      imageonerb,
      imagetworb,
      imagethreerb,
      imagefourrb,
      imagefiverb,
      imagesixrb,
      imagesevenrb,
      imageeightrb,
      imageninerb,
      imagetenrb,
    ],
    description:
      "HOUSE ON SALE, 20M, NEWLY BUILT HOUSE, 5 bedroom all ensuite, With an Extension of 3 units of 1 bedroom rentals",
    location:
      "Ruiru Bypass kamakis, 3Km from Thika rd, And 2km from Newly tarmacked Karuguru road",
    price: "20M",
    parking: "Parking is massive",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "50 by 100 plot, Ready title, Electricity connected, Spacious Open plan kitchen fitted with wall to wall modern cabinets, Pantry room, Laundry area, Common separate toilet and bathroom, Guest room is spacious and fitted with wall to wall closet, First floor consists, Friendly staircases, Open spacious window that gives penetrating light, All bedrooms are ensuite fitted with wall to wall closet, With a large balcony, Common separate toilet and bathroom, Master bedroom is ensuite fitted with wall to wall closet, All bathrooms are fitted with hot shower, Alarm door bell, Security alarm, Compound with cabro, Its  close vicinity to Quick  mart shopping mall, schools and worship places,ASKING PRICE 20M",
  },
  {
    id: 9,
    images: [
      imageonermk,
      imagetwormk,
      imagethreermk,
      imagefourrmk,
      imagefivermk,
      imagesixrmk,
      imagesevenrmk,
      imageeightrmk,
      imageninermk,
      imagetenrmk,
    ],
    description: "HOUSE ON SALE, 7.5M, Newly built, 3 bedroom master ensuite",
    location: "Ruiru Matangi, 3.5km from Thika rd, Along Kimbo matangi tarmac",
    price: "7.5M",
    parking: "3 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "40 by 60 plot, Ready title, Electricity connected,Internet services available, Sitting room is spacious, Spacious dining room table, Open plan spacious kitchen fitted with wall to wall cabinets, Unique  finishes, Gypsum ceiling, Chadaria bulbs, Superb painting and effects, Pantry room, Laundry area, Common separate toilet and bathroom, All bedrooms are fitted with wall to wall wardrobes, Spacious Master bedroom is ensuite fitted with wall to wall wardrobes, Hot shower connected, Perimeter wall, Security alarm system, Alarm door bell, The house is close vicinity to Spur shopping mall, Wankan school,Bethlehem school and worship places, ASKING  PRICE 7.5M",
  },
  {
    id: 11,
    images: [
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore4.jpg?alt=media&token=1000510e-5f5d-4249-a7a6-2d5019da64c9",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore6.jpg?alt=media&token=4f63b783-7e42-4f3d-8332-aa88f03b10db",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore5.jpg?alt=media&token=f2ae9dc4-6e5b-424f-8670-9e7f5d0f1954",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore7.jpg?alt=media&token=fe75ea54-1a01-43f8-8f0e-9f8248b2b1ad",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore1.jpg?alt=media&token=c5e1f965-d50a-40a6-aff8-3bf767b2b75a",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore2.jpg?alt=media&token=10b5d9a8-885b-44c4-82a4-40b77b4c3afb",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore3.jpg?alt=media&token=614cfd6c-d522-45df-8248-009625aed084",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore8.jpg?alt=media&token=3478105b-f829-435e-8d98-c0dc10af4935",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore9.jpg?alt=media&token=47d1be52-1673-445f-a20f-b900d2320bca",
      "https://firebasestorage.googleapis.com/v0/b/pushnotifications-3134c.appspot.com/o/jujamastore10.jpg?alt=media&token=7d28563a-b81b-48da-882b-f0d0b4e7bb5a",
    ],
    description:
      "HOUSE ON SALE, 10M neg, Newly built, 3 bedroom master ensuite",
    location: "Juja Mastore",
    price: "10M",
    parking: "3 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: `10M neg, Newly built, 3 bedroom master ensuite,  In Juja Mastore, 4km from Thika rd, Along newly built Juja tarmac,40 by 120 plot
    Ready title, 
    Water supply is sufficient, 
    Electricity connected,
    Internet services available,
    Parking is massive, 
    Sitting room is spacious, 
    Spacious dining room table, 
    Open plan spacious kitchen fitted with wall to wall cabinets,
    Unique  finishes, 
    Gypsum ceiling, 
    Chadaria bulbs, 
    Superb painting and effects,
    Pantry room, 
    Laundry area,
    Common separate toilet and bathroom,
    All bedrooms are fitted with wall to wall wardrobes, 
    Spacious Master bedroom is ensuite fitted with wall to wall wardrobes, 
    Hot shower connected, 
    Perimeter wall, 
    Security alarm system, 
    Alarm door bell, 
    The house is close vicinity to Juja shopping mall,Juja Preparatory school and worship places,
    ASKING  PRICE 10M neg.`,
  },
];
