import {
  imageone,
  imagetwo,
  imagethree,
  imagefour,
  imagefive,
  imagesix,
  imageseven,
  imageeight,
  imagenine,
  imageten,
} from "../../images/RuiruMugutha";
import {
  imageonerm,
  imagetworm,
  imagethreerm,
  imagefourrm,
  imagefiverm,
  imagesixrm,
  imagesevenrm,
  imageeightrm,
  imageninerm,
  imagetenrm,
} from "../../images/RuiruMwmbley";
import {
  imageonerk,
  imagetwork,
  imagethreerk,
  imagefourrk,
  imagefiverk,
  imagesixrk,
  imagesevenrk,
  imageeightrk,
  imageninerk,
  imagetenrk,
} from "../../images/RuiruKimbo";
import {
  imageonek,
  imagetwok,
  imagethreek,
  imagefourk,
  imagefivek,
  imagesixk,
} from "../../images/Katani";
import {
  imageonerms,
  imagetworms,
  imagethreerms,
  imagefourrms,
} from "../../images/RuiruMwmbleySale";
import {
  imageonermj,
  imagetwormj,
  imagethreermj,
  imagefourrmj,
  imagefivermj,
  imagesixrmj,
  imagesevenrmj,
  imageeightrmj,
  imageninermj,
  imagetenrmj,
} from "../../images/RuiruMatangiJunction";
import {
  imageonermsec,
  imagetwormsec,
  imagethreermsec,
  imagefourrmsec,
  imagefivermsec,
  imagesixrmsec,
  imagesevenrmsec,
  imageeightrmsec,
  imageninermsec,
  imagetenrmsec,
} from "../../images/RuiruMatangi";
import {
  imageonerb,
  imagetworb,
  imagethreerb,
  imagefourrb,
  imagefiverb,
  imagesixrb,
  imagesevenrb,
  imageeightrb,
  imageninerb,
  imagetenrb,
} from "../../images/RuiruBypassKamakis";
import {
  imageonermk,
  imagetwormk,
  imagethreermk,
  imagefourrmk,
  imagefivermk,
  imagesixrmk,
  imagesevenrmk,
  imageeightrmk,
  imageninermk,
  imagetenrmk,
} from "../../images/RuiruMatangiKimbo";

export const data = [
  {
    id: 1,
    images: [
      imageone,
      imagetwo,
      imagethree,
      imagefour,
      imagefive,
      imagesix,
      imageseven,
      imageeight,
      imagenine,
      imageten,
    ],
    description: `HOUSE ON SALE,
    9M,
    3 bedroom master ensuite `,
    location: "In Kenyatta Rd Muigai Inn",
    price: "9M",
    parking: "4 cars",
    security: "Security with guards 24hrs",
    water: "Water flowing 24hrs",
    more: `40/80 plot
    Ready title, In a gated controlled  development community 
    3.5 km from Thika Rd, 
    From tarmac its 400 metres,
    Water supply plenty and sufficient, 
    Electricity connected, 
    Internet services available, 
    Parking of 4 cars, 
    Sitting room is spacious, 
    Spacious dining room table, 
    Open plan spacious kitchen fitted with wall to wall cabinets,
    Unique  finishes,  
    Superb painting and effects,
    Chandaria bulbs, 
    Pantry room, 
    Laundry area, 
    Common separate toilet and bathroom, 
    All bedrooms are ensuite fitted with wall to wall wardrobes, 
    Spacious Master bedroom is ensuite fitted with wall to wall wardrobes, 
    Hot shower connected, 
    Perimeter wall, 
    Security alarm system,
    Alarm door bell, 
    Compound with ballast,
    The house is close vicinity to Juja Shopping mall,Juja Preparatory ,Precious Blood schools and worship places `,
  },
  {
    id: 2,
    images: [
      imageonerm,
      imagetworm,
      imagethreerm,
      imagefourrm,
      imagefiverm,
      imagesixrm,
      imagesevenrm,
      imageeightrm,
      imageninerm,
      imagetenrm,
    ],
    description: "HOUSE ON SALE 13.5M, Brand New house 4 bedroom all ensuite",
    location: "Ruiru Matangi, 3.5Km from Thika rd",
    price: "13.5M",
    parking: "3 cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: `40 by 60 plot Ready title, Water supply sufficient, Security with guards, 
    Parking of 3 cars,
    Lounge is spacious, 
    Dinning room table, 
    With unique finishes and design,
    Chandaria bulbs, 
    Gypsum ceiling, 
    Tiled floor, 
    Open plan kitchen fitted with wall to wall cabinets, 
    Pantry room, 
    Laundry area,
    Common separate toilet and bathroom,
    Guest room is spacious and fitted with wall to wall closet,
    First floor consists, 
    Friendly staircases, 
    Open spacious window that gives penetrating light, 
    All bedrooms are fitted with wall to wall closet,
    With a large balcony,
    Common separate toilet and bathroom, 
    Master bedroom is ensuite fitted with wall to wall closet, 
    All bathrooms are fitted with hot shower, 
    Alarm door bell, 
    Security alarm, 
    Compound with cabro, 
    Its  close vicinity to Spur shopping mall, Wanaka school Bethlehem schools and worship places.`,
  },
  {
    id: 3,
    images: [imageonerms, imagetworms, imagethreerms, imagefourrms],
    description:
      "HOUSE ON SALE 17M NEWLY BUILT 4 bedroom all ensuite With a self contained SQ rooftop",
    location: "Ruiru Mwmbley 1 km from Thika Rd 400 metres from Eastern bypass",
    price: "17M",
    parking: "4 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "40*80 plot size ,Lounge is spacious, Dinning room table, With unique finishes and design, Chandaria bulbs, Gypsum ceiling, Tiled floor, Open plan kitchen fitted with wall to wall cabinets, Pantry room, Laundry area, Common separate toilet and bathroom, Guest room is spacious and fitted with wall to wall closet, First floor consist, Friendly staircases, Open spacious window that gives penetrating light, All bedrooms are ensuite fitted with wall to wall closet, With a large balcony, Common separate toilet and bathroom, Master bedroom is ensuite fitted with wall to wall closet, Master bathroom with bathtub, All bathrooms are fitted with hot shower, Alarm door bell, Security alarm, Compound with cabro, Its  close vicinity to Naivas shopping mall, schools and worship places, ASKING PRICE 17M",
  },
  {
    id: 4,
    images: [
      imageonek,
      imagetwok,
      imagethreek,
      imagefourk,
      imagefivek,
      imagesixk,
    ],
    description:
      "HOUSE ON SALE, 23M, NEWLY BUILT HOUSE, 4 bedroom all ensuite Plus self contained DSQ",
    location: "Katani",
    price: "23M",
    parking: "Parking is massive",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "In a 2 plots of 40 by 60 plot, Ready title, Lounge is spacious, Dinning room table, With unique finishes and design, Chandaria bulbs, Gypsum ceiling, Tiled floor, Spacious Open plan kitchen fitted with wall to wall modern cabinets, Pantry room, Laundry area, Common separate toilet and bathroom, Guest room is spacious and fitted with wall to wall closet, First floor consists, Friendly staircases, Open spacious window that gives penetrating light, All bedrooms are ensuite fitted with wall to wall closet, With a large balcony, Common separate toilet and bathroom, Master bedroom is ensuite fitted with wall to wall closet, All bathrooms are fitted with hot shower, Alarm door bell, Security alarm, Compound with cabro, Its close vicinity to shopping malls, schools and worship places, ASKING PRICE 23M",
  },
  {
    id: 5,
    images: [
      imageonerk,
      imagetwork,
      imagethreerk,
      imagefourrk,
      imagefiverk,
      imagesixrk,
      imagesevenrk,
      imageeightrk,
      imageninerk,
      imagetenrk,
    ],
    description:
      "HOUSE ON SALE, 35M, NEWLY BUILT 5 bedroom all ensuite with DSQ",
    location: "Ruiru Kimbo",
    price: "35M",
    parking: "Parking is massive",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "1/4acre, Ready title, Lounge is spacious, Dinning room table, Unique finishes, Gypsum ceiling, Wall to wall kitchen cabinets, Open kitchen, Pantry room, Study room, Laundry area, Cloakroom for the guest, Wall to wall wardrobes, Master bedroom is ensuite and bathtub fitted with wall to wall wardrobes, Master bathroom with jacuzzi, Balcony area is large and extensive, Compound is concrete and with cabro, Well manicured lawn and flower garden, Its close proximity to shopping malls,schools and worship places, SELLING PRICE 35M ",
  },
  {
    id: 6,
    images: [
      imageonermsec,
      imagetwormsec,
      imagethreermsec,
      imagefourrmsec,
      imagefivermsec,
      imagesixrmsec,
      imagesevenrmsec,
      imageeightrmsec,
      imageninermsec,
      imagetenrmsec,
    ],
    description: "HOUSE ON SALE 11M AFFORDABLE MANSIONATE NEWLY BUILT HOUSE",
    location: "Ruiru Matangi, 3.5Km from Thika rd",
    price: "11M",
    parking: "3 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "Lounge is spacious, Dinning room table With unique finishes and design, Chandaria bulbs Gypsum ceiling, Tiled floor, Spacious Open plan kitchen fitted with wall to wall modern cabinets, Pantry room, Laundry area, Common separate toilet and bathroom, Guest room is spacious and fitted with wall to wall closet, First floor consists, Friendly staircases, Open spacious window that gives penetrating light, All bedrooms are fitted with wall to wall closet, With a large balcony, Common separate toilet and bathroom, Master bedroom is ensuite fitted with wall to wall closet, All bathrooms are fitted with hot shower, Alarm door bell, Security alarm, Compound with cabro, Its  close vicinity to Spur shopping mall, Wanaka school Bethlehem schools and worship places",
  },
  {
    id: 7,
    images: [
      imageonermj,
      imagetwormj,
      imagethreermj,
      imagefourrmj,
      imagefivermj,
      imagesixrmj,
      imagesevenrmj,
      imageeightrmj,
      imageninermj,
      imagetenrmj,
    ],
    description:
      "HOUSE ON SALE, 6.5M, NEWLY BUILT FLAT ROOF,3 bedroom, master ensuite",
    location: "Ruiru Matangi Junction",
    price: "6.5M",
    parking: "4 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "40 by 60 plot, Ready title, Electricity connected, Internet services available, Sitting room is spacious, Spacious dining room table, Open plan spacious kitchen fitted with wall to wall cabinets, Unique  finishes, Chadaria bulbs, Superb painting and effects,  Laundry area, Common separate toilet and bathroom, All bedrooms are fitted with wall to wall wardrobes, Spacious Master bedroom is ensuite fitted with wall to wall wardrobes, Hot shower connected, Perimeter wall, Security alarm system, Alarm door bell, ASKING  PRICE 6.5M",
  },
  {
    id: 8,
    images: [
      imageonerb,
      imagetworb,
      imagethreerb,
      imagefourrb,
      imagefiverb,
      imagesixrb,
      imagesevenrb,
      imageeightrb,
      imageninerb,
      imagetenrb,
    ],
    description:
      "HOUSE ON SALE, 20M, NEWLY BUILT HOUSE, 5 bedroom all ensuite, With an Extension of 3 units of 1 bedroom rentals",
    location:
      "Ruiru Bypass kamakis, 3Km from Thika rd, And 2km from Newly tarmacked Karuguru road",
    price: "20M",
    parking: "Parking is massive",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "50 by 100 plot, Ready title, Electricity connected, Spacious Open plan kitchen fitted with wall to wall modern cabinets, Pantry room, Laundry area, Common separate toilet and bathroom, Guest room is spacious and fitted with wall to wall closet, First floor consists, Friendly staircases, Open spacious window that gives penetrating light, All bedrooms are ensuite fitted with wall to wall closet, With a large balcony, Common separate toilet and bathroom, Master bedroom is ensuite fitted with wall to wall closet, All bathrooms are fitted with hot shower, Alarm door bell, Security alarm, Compound with cabro, Its  close vicinity to Quick  mart shopping mall, schools and worship places,ASKING PRICE 20M",
  },
  {
    id: 9,
    images: [
      imageonermk,
      imagetwormk,
      imagethreermk,
      imagefourrmk,
      imagefivermk,
      imagesixrmk,
      imagesevenrmk,
      imageeightrmk,
      imageninermk,
      imagetenrmk,
    ],
    description: "HOUSE ON SALE, 7.5M, Newly built, 3 bedroom master ensuite",
    location: "Ruiru Matangi, 3.5km from Thika rd, Along Kimbo matangi tarmac",
    price: "7.5M",
    parking: "3 Cars",
    security: "Security with guards 24hrs",
    water: "Water flow supply is sufficient ",
    more: "40 by 60 plot, Ready title, Electricity connected,Internet services available, Sitting room is spacious, Spacious dining room table, Open plan spacious kitchen fitted with wall to wall cabinets, Unique  finishes, Gypsum ceiling, Chadaria bulbs, Superb painting and effects, Pantry room, Laundry area, Common separate toilet and bathroom, All bedrooms are fitted with wall to wall wardrobes, Spacious Master bedroom is ensuite fitted with wall to wall wardrobes, Hot shower connected, Perimeter wall, Security alarm system, Alarm door bell, The house is close vicinity to Spur shopping mall, Wankan school,Bethlehem school and worship places, ASKING  PRICE 7.5M",
  },
];
